### ISSUE TITLE
☂️ Replace Plutono with Perses

### ISSUE THREAD

**Issue by vicwicker** [gardener/monitoring#24]
#### What would you like to be added:

Perses is a dashboard to visualize observability data with support for Prometheus metrics. Perses is a CNCF sandbox project and should replace Plutono in Gardener.

#### Why is this needed:

Our current data visualisation tool, Plutono, is a fork from Grafana. It was adopted as an alternative when Grafana underwent a major licensing change. However, Plutono is limited to security patches, with no new feature additions. This constraint prevents us from consuming the most recent developments in data visualisation and dashboard management.

#### Tasks:

- [x] Evaluate [Perses](https://perses.dev/)
- [x] https://github.com/gardener/monitoring/issues/23
- [ ] Deploy Perses as a drop-in next to Plutono
  - [ ] https://github.com/gardener/monitoring/issues/47 
- [ ] https://github.com/gardener/monitoring/issues/49
- [ ] Evaluate using single Perses instance per Seed
- [ ] Remove Plutono

**Comment by rickardsjp** [comment]
closed in favor of https://github.com/gardener/monitoring/issues/52
