### ISSUE TITLE
Rewrite `gardener-metrics-exporter` metrics as `CustomResourceState` metrics

### ISSUE THREAD

**Issue by vicwicker** [gardener/monitoring#27]
We might be able to _deprecate_ the Gardener / SAP proprietary project: https://github.com/gardener/gardener-metrics-exporter, and replace its functionality with the community driven https://github.com/kubernetes/kube-state-metrics project.

The recent feature, [customresourcestate-metrics.md](https://github.com/kubernetes/kube-state-metrics/blob/v2.12.0/docs/customresourcestate-metrics.md), might be flexible enough to implement the features of the gardener metrics exporter.

This could be beneficial, because
- we could use a community managed component for standard Kubernetes tasks (expose attributes of (custom) resources for Prometheus), instead of maintaining a proprietary (although open source, but not widely adopted) project
- adding new features (like exposing attributes of the `Garden` resource) could be much more straightforward than with the current proprietary approach

**Tasks:**

- [ ] Confirm that all the currently exposed gme metrics can be implemented with a CRS configuration
  - reviewing and changing the metric and label names could be OK.
  - [ ] Consider the migration options for this probably breaking change (e.g. deploy both exporters for some time in parallel or adjust the dashboards and recording rules to cope with the breaking change)
- [x] Let the gardener-operator deploy a ksm: `garden-runtime-kube-state-metrics`, to the runtime garden cluster, expose regular pod metrics and the conditions of the Garden resource. Let the garden Prometheus scrape these metrics.
- [x] Let the gardener-operator deploy a ksm: `garden-virtual-kube-state-metrics`, to the runtime garden cluster, configure it to talk to the virtual garden cluster expose metrics about seeds, shoots, ... that used to be exposed by the gardener-metrics-exporter. Let the garden Prometheus scrape these metrics.

![Image](https://github.com/user-attachments/assets/d2033975-788a-4963-aa06-a30f53006b3e)

**Comment by chrkl** [comment]
We will discontinue this initiative in favor of OpenTelemetry (https://github.com/gardener/monitoring/issues/57). Current limitations for kube-state-metrics regarding API aggregation layer monitoring (https://github.com/kubernetes/kube-state-metrics/issues/2471) do not allow to make this replacement as planned.
