### ISSUE TITLE
Add alerts about Prometheus issues

### ISSUE THREAD

**Issue by vicwicker** [gardener/monitoring#33]
We should alert if the Prometheus instances deployed in the seeds or the garden cluster have issues. Otherwise we risk missing some relevant data.

<details>
<summary>Here is a screenshot from the internal discussion we had</summary>

![Image](https://github.com/user-attachments/assets/ce27a49d-1e82-44a3-b160-93b971bd7ffd)

</details>

**Tasks**

- [x] Check if we get an alert if one of the prometheus in the seed is unhealthy. If not, then add the alert.
- [x] Rework seed alerts to consider all possible conditions: https://github.com/gardener/gardener/pull/9750
  - [x] Double check this end-to-end in the dev landscape: break a cache Prometheus by ignoring the managed resource and e.g. tweaking the container image, and assert that an alert is sent to Slack.
- [x] Check the alerts for the Prometheus instances in the runtime garden cluster: https://github.com/gardener/gardener/pull/10562
- [ ] Check conditions based on the metrics inside Prometheus

**Comment by chrkl** [comment]
@vicwicker @istvanballok any plans to continue with the last open task or can we close this?

**Comment by vicwicker** [comment]
> [@vicwicker](https://github.com/vicwicker) [@istvanballok](https://github.com/istvanballok) any plans to continue with the last open task or can we close this?

Let's close it. I think we could argue the last item overlaps with:

- https://github.com/gardener/gardener/pull/13341

/close
