### ISSUE TITLE
Add a seed Plutono dashboard to show the memory usage of the pods on a seed node

### ISSUE THREAD

**Issue by vicwicker** [gardener/monitoring#37]
We should add a dashboard to the seed Plutono that shows the CPU and Memory usage of the pods on a seed node.

Note that
- the control plane Prometheus does not have this information, because we should not leak information about other control planes to the stakeholder.
- The cache Prometheus has these metrics, but it does not retain them for long and there is no such Plutono dashboard. We should not retain the metrics for longer, because it would contradict the role of the cache Prometheus.
- The aggregate Prometheus does not federate these metrics to avoid having too many metrics but this is the default data source for the seed Plutono.
- The seed Prometheus is not federating these metrics either.

**Tasks:**

- [ ] Decide whether the aggregate or the seed Prometheus would be a better match to federate this specific metrics. The aggregate Prometheus would probably be OK.
- [ ] Federate these metrics to the aggregate Prometheus: CPU and Memory usage `cadvisor` metrics and the CPU and Memory request `ksm` metrics
- [ ] Add a dashboard to show the pods of a specific node.
- [ ] Maybe for convenience, add a dropdown for the shoot control plane namespaces, and then it could show the seed nodes where the API servers of that control plane were running, in the specified interval. This would make it very straighforward to answer the question that motivated the issue. Use maybe thicker lines to show the resource usage of the pods of the selected control plane, to easily differentiate them from the neighbours.
