### ISSUE TITLE
Drop the numerous API server metrics: `apiserver_request_duration_seconds_bucket`

### ISSUE THREAD

**Issue by vicwicker** [gardener/monitoring#41]
The Kubernetes API server exposes a _histogram_ metric: `request_duration_seconds` in [kubernetes/apiserver/pkg/endpoints/metrics/metrics.go](https://github.com/kubernetes/kubernetes/blob/c9a1a0a3b8acb70cba30d6f4ea59505b4564b4d9/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go#L96-L108), that captures the HTTP request durations, broken down by several dimensions, e.g. `verb` (like GET, WATCH) and `resource` (like pod, ...). The cardinality of these labels is multiplied and it results in a significant number of time series.

The `_buckets` suffix time series of the [histogram](https://prometheus.io/docs/concepts/metric_types/#histogram) metric captures the request duration in 23 time buckets: `5ms` .. `60s`.
 
```text
seconds: 0.005, 0.025, 0.05, 0.1, 0.2, 0.4, 0.6, 0.8, 1.0, 1.25, 1.5, 2, 3, 4, 5, 6, 8, 10, 15, 20, 30, 45, 60
```

This factor `x23` makes the `apiserver_request_duration_seconds_bucket` time series the most numerous in Prometheus: e.g. 40k or ~40% in an example.

![Image](https://github.com/user-attachments/assets/037afe07-fa65-47dc-8a17-8e8de1cfed19)

Actually, we could challenge if the resolution that these buckets allow are worth their "price".

They are used to visualize the _distribution_ of the request duration in heatmaps e.g. on this dashboard: [apiserver-request-duration-and-response-size.json](https://github.com/gardener/gardener/blob/17f19ee198835e8d03b6f743fd8c1c1f39c91fe1/pkg/component/observability/plutono/dashboards/garden-shoot/apiserver-request-duration-and-response-size.json#L106-L107)

We could argue that
- the distribution of a single request group, e.g. `LIST` `pods`, is not expected to be spread out or to have multiple centers. (This could be in an anomaly, but this is unlikely and I can not recall a RCA that relied on such a case.) So even if the hard coded bucket boundaries provide a good resolution in the relevant time range, the average request duration (`..._sum / ..._count`) could be good enough instead of the histogram with the buckets, assuming that the distribution can be well characterized with the average value.
- the heatmap visualisation of a distribution containing multiple verbs and resources is probably more spread out / colorful, but actually not so meaningful so it is not worth showing that: the distribution or the average value of unrelated requests (like a `WATCH` that is kept open for over a minute or a `GET` that is processed in less than 1s) is not so interesting.
- it is confusing that `WATCH` requests fall into the `60s ... +Inf` bucket and hence in the heatmap or with `histogram_quantile` functions show up as `60s`, the lower boundary of the `+Inf` bucket. Here actually the average value gives a more exact pictures because the hard coded bucket boundaries are not a good fit for intentionally long running (typically ~5m) `WATCH` requests

Note that the open source Kubernetes control plane monitoring project, `kube-prometheus`, dropped these metrics in 2020: [kube-prometheus/387](https://github.com/prometheus-operator/kube-prometheus/pull/387/files) and they are still dropped in 2024: [kube-prometheus/k8s-control-plane.libsonnet](https://github.com/prometheus-operator/kube-prometheus/blob/c523c26a33f9018e6171c1b7c002e5128dfa83a4/jsonnet/kube-prometheus/components/k8s-control-plane.libsonnet#L266-L267). (Note that the bucket boundaries have diverged in the meantime and the kube-prometheus project maintainers missed to update the configuration.)

**Tasks:**

- [ ] Drop the `_bucket` time series of high cardinality histogram metrics (also `etcd_request_duration_seconds_bucket`)
  - Dropping these metrics in a relabeling rule avoids the storage costs in Prometheus, but they still need to be scraped from the API server
    - [ ] Maybe: Check in an issue with Kubernetes whether these high cardinality metrics could be made optional
- [ ] Adjust the Plutono dashboards: instead of using the heatmap visualisation for histograms, we could show the average duration values as a regular graph

Related: https://github.com/gardener/gardener/pull/10009
